LBApp/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace LBApp.Models;

public partial class Book
{
    public int BookId { get; set; }
    [Required(ErrorMessage ="Поле не повинно бути порожнім")]
    [Display(Name ="Назва книги")]
    public string BookName { get; set; } = null!;
    [Required(ErrorMessage = "Поле не повинно бути порожнім")]
    [Display(Name = "Рік написання")]
    public int BookYear { get; set; }
    [Required(ErrorMessage = "Поле не повинно бути порожнім")]
    [Display(Name = "Ціна книги")]
    public double BookPrice { get; set; }
    [Required(ErrorMessage = "Поле не повинно бути порожнім")]
    [Display(Name = "Назва жанру")]
    public int GenreId { get; set; }
    
    [Display(Name = "Кількість сторінок")]
    public int? BookPagesCount { get; set; }
    
    [Display(Name = "Назва видавництва")]
    public int? PublishingHouseId { get; set; }
    [Display(Name = "Ім'я авторів")]
    public virtual ICollection<AuthorsBook> AuthorsBooks { get; } = new List<AuthorsBook>();
    [Display(Name = "Коментарі")]
    public virtual ICollection<Comment> Comments { get; } = new List<Comment>();
    
    [Display(Name = "Назва жанру")]
    public virtual Genre Genre { get; set; } = null!;

    [Display(Name = "Назва видавництва")]
    public virtual PublishingHouse? PublishingHouse { get; set; }

    public virtual ICollection<ReadersBook> ReadersBooks { get; } = new List<ReadersBook>();
}

LBApp/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LBApp.Models;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Authorization;

namespace LBApp.Controllers
{
    //[Authorize(Roles="admin")]
    public class GenresController : Controller
    {
        private readonly DblibraryContext _context;

        public GenresController(DblibraryContext context)
        {
            _context = context;
        }

        // GET: Genres
        public async Task<IActionResult> Index()
        {
            return _context.Genres != null ?
                        View(await _context.Genres.ToListAsync()) :
                        Problem("Entity set 'DblibraryContext.Genres'  is null.");
        }

        // GET: Genres/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Genres == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            //return View(genre);
            return RedirectToAction("Index", "Books", new { id = genre.GenreId, name = genre.GenreName });
        }

        // GET: Genres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GenreId,GenreName,GenreDescr")] Genre genre)
        {
            if (_context.Genres.Where(b => genre.GenreName == b.GenreName).Count() > 0)
            {
                ModelState.AddModelError("GenreName", "Жанр з таким ім'ям вже існує");
            }
            if (ModelState.IsValid)
            {
                _context.Add(genre);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Genres == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GenreId,GenreName,GenreDescr")] Genre genre)
        {
            if (id != genre.GenreId)
            {
                return NotFound();
            }
            var namee = _context.Genres.Where(b => genre.GenreName == b.GenreName);
            if (namee.Count() > 0 && namee.Where(b => b.GenreId == id).Count() == 0)
            {
                ModelState.AddModelError("GenreName", "Жанр з таким ім'ям вже існує");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(genre);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GenreExists(genre.GenreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        // GET: Genres/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Genres == null)
            {
                return NotFound();
            }

            var genre = await _context.Genres
                .FirstOrDefaultAsync(m => m.GenreId == id);
            if (genre == null)
            {
                return NotFound();
            }

            return View(genre);
        }

        // POST: Genres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Genres == null)
            {
                return Problem("Entity set 'DblibraryContext.Genres'  is null.");
            }
            var genre = await _context.Genres.FindAsync(id);
            if (_context.Books.Where(b => b.GenreId == genre.GenreId).Count() > 0)
            {
                //return Problem("У цього автора є книги");
                ModelState.AddModelError("GenreId", "Неможливо видалити, існують книги цього жанру");
                return View(genre);
            }
            if (genre != null)
            {
                _context.Genres.Remove(genre);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GenreExists(int id)
        {
            return (_context.Genres?.Any(e => e.GenreId == id)).GetValueOrDefault();
        }


        public bool check(string s1, string s2)
        {
            string[] ss1 = s1.Split(' ');
            string[] ss2 = s2.Split(' ');
            Array.Sort(ss1);
            Array.Sort(ss2);
            return ss1.SequenceEqual(ss2);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {

            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {
                    using (var stream = new FileStream(fileExcel.FileName, FileMode.Create))
                    {
                        await fileExcel.CopyToAsync(stream);
                        using (XLWorkbook workBook = new XLWorkbook(stream))
                        {
                            //перегляд усіх листів (в даному випадку категорій)
                            foreach (var wst in workBook.Worksheets)
                            {
                                Genre genre = new Genre();
                                var f = (from t in _context.Genres where t.GenreName.Contains(wst.Name) select t).FirstOrDefault();
                                if (f != default(Genre))
                                {
                                    genre = f;
                                }
                                else
                                {
                                    genre.GenreName = wst.Name;
                                    genre.GenreDescr = "Genre from Excel";
                                    _context.Genres.Add(genre);

                                }

                                foreach (IXLRow row in wst.RowsUsed().Skip(1))
                                {
                                    try
                                    {
                                        Book book = new Book();
                                        book.BookName = row.Cell(1).Value.ToString();
                                        book.BookPagesCount = Convert.ToInt32(row.Cell(2).Value.ToString());
                                        book.BookPrice = Convert.ToInt32(row.Cell(3).Value.ToString());
                                        book.BookYear = Convert.ToInt32(row.Cell(4).Value.ToString());
                                        book.Genre = genre;
                                        int flag = 0;
                                        if (_context.Books.Where(b => book.BookName == b.BookName).Count() > 0)
                                        {
                                            flag = 1; 
                                        }
                                        if (book.BookYear < 0 || book.BookYear > DateTime.Now.Year)
                                        {
                                            flag = 1; 
                                        }
                                        if (book.BookPrice < 0)
                                        {
                                            flag = 1;
                                        }
                                        if (book.BookPagesCount < 0)
                                        {
                                            flag = 1;
                                        }
                                        if (flag==0) { _context.Books.Add(book);

                                            int start = 5;
                                            int fin = 7;
                                            for (int i = start; i <= fin; i++)
                                            {
                                                if (row.Cell(i).Value.ToString().Length > 0)
                                                {
                                                    Models.Author auth = new Models.Author();
                                                    var a = (from aut in _context.Authors where aut.AuthorName.Contains(row.Cell(i).Value.ToString()) select aut).FirstOrDefault();
                                                    if (a != default(Models.Author))
                                                    {

LBApp/Views/Books/Create.cshtml
@model LBApp.Models.Book

@{
    ViewData["Title"] = "Створення";
}

<h1>Додати книгу жанру @ViewBag.GenreName</h1>

<h4>Книга</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookName" class="control-label"></label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookYear" class="control-label"></label>
                <input asp-for="BookYear" class="form-control" />
                <span asp-validation-for="BookYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookPrice" class="control-label"></label>
                <input asp-for="BookPrice" class="form-control" />
                <span asp-validation-for="BookPrice" class="text-danger"></span>
            </div>
            <input type="hidden" value="@ViewBag.GenreId" name="GenreId"/>
            <div class="form-group">
                <label asp-for="BookPagesCount" class="control-label"></label>
                <input asp-for="BookPagesCount" class="form-control" />
                <span asp-validation-for="BookPagesCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingHouseId" class="control-label"></label>
                <select asp-for="PublishingHouseId" class ="form-control" asp-items="ViewBag.PublishingHouseId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Повернутись назад", "Index","Books", new {id= @ViewBag.GenreId, name=@ViewBag.GenreName})
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LBApp/Views/Books/Delete.cshtml
@model LBApp.Models.Book

@{
    ViewData["Title"] = "Видалення";
}

<h1>Видалення</h1>

<h3>Ви впевнені?</h3>
<div>
    <h4>Книга</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookPagesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookPagesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingHouse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishingHouse.PhName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BookId" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        @Html.ActionLink("Повернутись назад", "Index","Books", new {id= @ViewBag.GenreId, name=@ViewBag.GenreName})
    </form>
</div>

LBApp/Views/Books/Details.cshtml
@model LBApp.Models.Book

@{
    ViewData["Title"] = "Деталі";
}

<h1>Деталі</h1>

<div>
    <h4>Книга</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookPagesCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookPagesCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublishingHouse)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublishingHouse.PhName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {id= Model?.BookId}) |
    @Html.ActionLink("Повернутись назад", "Index","Books", new {id= @ViewBag.GenreId, name=@ViewBag.GenreName})
</div>

LBApp/Views/Books/Edit.cshtml
@model LBApp.Models.Book

@{
    ViewData["Title"] = "Редагування";
}

<h1>Редагування</h1>

<h4>Книга</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BookId" />
            <div class="form-group">
                <label asp-for="BookName" class="control-label"></label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookYear" class="control-label"></label>
                <input asp-for="BookYear" class="form-control" />
                <span asp-validation-for="BookYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookPrice" class="control-label"></label>
                <input asp-for="BookPrice" class="form-control" />
                <span asp-validation-for="BookPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-for="GenreId" class="form-control" asp-items="ViewBag.GenreId"></select>
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookPagesCount" class="control-label"></label>
                <input asp-for="BookPagesCount" class="form-control" />
                <span asp-validation-for="BookPagesCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublishingHouseId" class="control-label"></label>
                <select asp-for="PublishingHouseId" class="form-control" asp-items="ViewBag.PublishingHouseId"></select>
                <span asp-validation-for="PublishingHouseId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Повернутись до книжок", "Index","Books", new {id= @ViewBag.GenreIdd, name=@ViewBag.GenreName})
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LBApp/Views/Books/Index.cshtml
@model IEnumerable<LBApp.Models.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Книги за жанром @ViewBag.GenreName</h1>
<div>
    <h3>Завантаження файлу: </h3>
    @Html.ActionLink("Завантажити", "Export", "Books", new {genreId=@ViewBag.GenreId})
</div>
@if (User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Додати нову книгу", "Create", "Books", new {genreId= @ViewBag.GenreId})
    </p>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookPagesCount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishingHouse)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookPagesCount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.GenreName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishingHouse.PhName)
            </td>
            
                @if (User.IsInRole("admin"))
                {
                    <td>
                        @Html.ActionLink("Edit", "Edit", new {id= @item.BookId}) |
                        @Html.ActionLink("Details", "Details", new {id= @item.BookId}) |
                        @Html.ActionLink("Delete", "Delete", new {id= @item.BookId})
                    </td>
                }
                else
                {
                    <td>
                        @Html.ActionLink("Details", "Details", new {id= @item.BookId})
                    </td>
                }
        </tr>
}
    </tbody>
</table>

<p>
    @Html.ActionLink("Повернутись назад", "Index", "Genres")
</p>